# This is a basic workflow to help you get started with Actions

name: elevate
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: msbuild Elevate\Elevate.vcxproj /t:rebuild /p:configuration=release /p:platform=win32

    - uses: actions/upload-artifact@v2
      with:
        name: elevate
        path: Elevate\bin\x86\release\elevate.exe

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: elevate
          path: Elevate\bin\x86\release\elevate.exe
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'Elevate\bin\x86\release\*.exe'
